### ISSUE TITLE
parany implementation

### ISSUE THREAD

**Issue by UnixJunkie** [ocaml-multicore/domainslib#2]
Hi there!
If you are interested, I'll try to send a parany implementation in there soon.

**Comment by UnixJunkie** [comment]
```
val Parany.run                                                               
    verbose:bool ->                                                             
    csize:int ->                                                                
    nprocs:int ->                                                               
    demux:(unit -> 'a) -> work:('a -> 'b) -> mux:('b -> unit) -> unit  
```

I would just need to know how to start a new thread.

**Comment by kayceesrk** [comment]
That would be useful. Domains can be created with `Domain.spawn`: https://github.com/ocaml-multicore/ocaml-multicore/blob/parallel_minor_gc/stdlib/domain.mli#L5

@sudha247 is working on the same. Some coordination may be useful in avoiding duplicate work. 

My idea of the design was to spawn the domains and then use a single shared channel to distribute the work to the workers. This is the idea used in Multicore version of Grammatrix: https://github.com/ocaml-bench/sandmark/blob/master/benchmarks/multicore-grammatrix/grammatrix_multicore.ml.

**Comment by kayceesrk** [comment]
@gasche Also expressed some interest in providing a high-level API.

**Comment by UnixJunkie** [comment]
@gasche will probably send a parmap version.
Since I am the author (and maintainer) of parany, I am interested by another interface.

**Comment by gasche** [comment]
I hope that over time (and sooner rather than later, if we want people to be able to experiment with the runtime) we get a diverse library of concurrency patterns (parfoo but also fork-join, etc.). For the very small program I wrote, parmap (and not parfold or pariter) was sufficient (with no chunking), and it is already a reasonably expressive primitive, so I thought it would be nice to start with this.

Now that I tried a few different things, I think that actually an even simpler primitive would be to build a "task pool", created with a fixed number of domains, exposing a channel to which users feed `(unit -> unit)` jobs (including, possibly, from within a job), with a `close` primitive to discard the pool once all already-received jobs are done.

**Comment by gasche** [comment]
@UnixJunkie I proposed an implementation of a simplistic paralllel `Array.map` in https://github.com/ocaml-multicore/ocaml-multicore/issues/324#issuecomment-610000766 , in case that can be useful to you.

(Also, unrelatedly: thanks for all your recent work on Batteries!)

**Comment by kayceesrk** [comment]
A simple parallel array processing library would be a good start. I suspect that many mathematical kernels can be expressed using this. Then, I’d like to port the parallel benchmarks in sandmark to use this rather than domains and channels. 

One thing I’ve been think is quite important but don’t Know how to do is parallel initialisation. I suspect that sequential initialisation costs would be prohibitive at large domain counts. The challenge is to prevent the GC from observing uninitialised parts of the array.

On the idea of generating jobs from within jobs, I like the Functory compute API (https://www.lri.fr/~filliatr/functory/doc/Functory.Sequential.html).

**Comment by gasche** [comment]
Here is an interface for a "task pool", in fact "domain pool", that can replace existing simple uses of Unix.fork() for parallelism:

```ocaml
(** A domain pool is in charge of spawning domains and sending jobs to them. *)
type t

(** [spawn num_domains] will create a pool of [num_domains] new domains. *)
val spawn : num_domains:int -> t

(** Send a job to be performed later,
    by the first available domain of the pool.

    @raise Invalid_argument if the domain pool has been joined.
*)
val send_job : t -> (unit -> unit) -> unit

(** Blocks until all jobs in the pool are done, and joins the
   domains. *)
val join : t -> unit
```

(It doesn't deal with generating jobs within jobs, which would have an interesting interaction with `join` that I don't know how to implement properly.)

I will implement this and try to change my previous toy benchmark to use it.

**Comment by kayceesrk** [comment]
I've implemented support for task pools: https://github.com/ocaml-multicore/domainslib/blob/task_pool/lib/task_pool.mli. The API may be a bit obscure on first-look, but this allows the implementation of both coarse-grained parallel programs (like parallel arrays and parallel for) and recursive-parallel programs. 

As an example of coarse-grained parallel program, I've ported Game of Life to use parallel forloop. The sequential loop https://github.com/ocaml-multicore/domainslib/blob/task_pool/test/game_of_life.ml#L47-L51 becomes a parallel for loop https://github.com/ocaml-multicore/domainslib/blob/task_pool/test/game_of_life_multicore.ml#L50-L54. And here is parallel recursive fibonacci, https://github.com/ocaml-multicore/domainslib/blob/task_pool/test/fib_par.ml. 

It should be easy to add parallel mapping and folding over arrays.

**Comment by kayceesrk** [comment]
Subsumed by #4. Hence, closing this issue. Feel free to open a PR for the Parany style API.

**Comment by UnixJunkie** [comment]
Indeed, parallel_for is a quite useful primitive. It is provided in OpenMP.
By the way, the interface of openmp could give you a list of standard and useful parallel primitives.

**Comment by kayceesrk** [comment]
Yeah. I need to read the OpenMP spec, at least for naming things sensibly. One primitive that I think would be quite useful is parallel scan. This prefix sum for shared memory processors gives a good basis to implement the more general parallel scan operation: https://en.wikipedia.org/wiki/Prefix_sum#Shared_memory:_Two-level_algorithm.

**Comment by UnixJunkie** [comment]
Might be useful:
https://www.openmp.org/wp-content/uploads/OpenMP-4.5-1115-CPP-web.pdf
